STATE:
  - VX
  - VY
  - YAW_RATE
  - THROTTLE_FB
  - STEERING_FB
ACTIONS:
  - THROTTLE_CMD
  - STEERING_CMD
PARAMETERS:
  - Mass:
    Min : 700 
    Max : 850
  - Bf:
    Min: 1.0
    Max: 20.0
  - Cf:
    Min: 0.1
    Max: 1.5
  - Df:
    Min: 10.0
    Max: 8000
  - Ef:
    Min: -2.0
    Max: 5
  - Br:
    Min: 1.0
    Max: 20.0
  - Cr:
    Min: 0.1
    Max: 1.5
  - Dr:
    Min: 10.0
    Max: 8000.0
  - Er:
    Min: -2.0
    Max: 10.0
  - Cm1:
    Min: 100.0
    Max: 10000.0  
  - Cm2:
    Min: 0.0
    Max: 5.0
  - Cr0:
    Min: 0.1
    Max: 1.4
  - Cr2:
    Min: 0.1
    Max: 1.0
  - Iz: 
    Min: 5000.0
    Max: 20000.0
  - Shf:
    Min: -0.02
    Max: 0.2
  - Svf: 
    Min: -2000.0
    Max: 300.0
  - Shr:
    Min: -0.02
    Max: 0.2
  - Svr:
    Min: -2000.0
    Max: 300.0
  - Qvx:
    Min: 0.1
    Max: 1
  - Qvy:
    Min: 0.1
    Max: 1
  - QyawRate:
    Min: 0.1
    Max: 1
  - Rvx:
    Min: 0.01
    Max: 1
  - Rvy:
    Min: 0.01
    Max: 1
  - RyawRate:
    Min: 0.0001
    Max: 0.01
VEHICLE_SPECS:
  lf: 1.248
  lr: 1.7328
  # mass: 790.0
MODEL:
  NAME: FTHDIAC
  HORIZON: 7
  LAYERS:
    - GRU:
      OUT_FEATURES: 49
      LAYERS: 2
    - DENSE:
      OUT_FEATURES: 211
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 211
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 211
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 211
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 211
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 211
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 211
      ACTIVATION: Mish
    - DENSE:
      OUT_FEATURES: 211
      ACTIVATION: Mish
  OPTIMIZATION:
    LOSS: MSE
    BATCH_SIZE: 32
    NUM_EPOCHS: 50
    # NUM_EPOCHS: 15000
    OPTIMIZER: Adam
    LR: 0.003674
